name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          npm ci
          npm run build
      - uses: ./
        id: package
        with:
          targetRepoOwner: "w3f"
          targetRepo: "Open-Grants-Program"
          prLink: "https://github.com/w3f/Open-Grants-Program/pulls/174"
          author: "mmagician"